sudo: required
dist: precise
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq build-essential cmake curl lcov

before_script:
  - export CXX=$COMPILER
  - git submodule update --init
  - mkdir build
  - cd build
  - cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug ..

script:
  - cmake --build .

after_script:
  - cmake --build . --target coveralls

notifications:
  email: false
