language: cpp

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get -qq update

install:
# update to gcc with C++11 support
- sudo apt-get -qq install gcc-4.9 g++-4.9
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90
- sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.9 90
# install latest LCOV (1.9 was failing)
- cd ${TRAVIS_BUILD_DIR}
- wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.13.orig.tar.gz
- tar xf lcov_1.13.orig.tar.gz 
- sudo make -C lcov-1.13/ install
# install coveralls-lcov
- gem install coveralls-lcov

before_script:
- cd ${TRAVIS_BUILD_DIR}
- lcov --directory . --zerocounters

script:
- cd ${TRAVIS_BUILD_DIR}
- cmake .
- make
- ctest --verbose

after_success:
- cd ${TRAVIS_BUILD_DIR}
- lcov --directory . --capture --output-file coverage.info
- lcov --remove coverage.info '**/usr/*' '**/test/*' '**/catch/*' '**/fakeit/*' --output-file coverage.info
- lcov --list coverage.info
- coveralls-lcov coverage.info
