language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9

before_install:
- sudo apt-get -qq update

install:
- sudo apt-get install -y -qq build-essential cmake lcov
- gem install coveralls-lcov

before_script:
- export CXX=$COMPILER
- cd ${TRAVIS_BUILD_DIR}
- lcov --directory . --zerocounters

script:
- cd ${TRAVIS_BUILD_DIR}
- cmake .
- make
- ctest --verbose

after_success:
- cd ${TRAVIS_BUILD_DIR}
- lcov --directory . --capture --output-file coverage.info
- lcov --remove coverage.info '**/usr/*' '**/test/*' '**/googletest-src/*' --output-file coverage.info
- lcov --list coverage.info
- coveralls-lcov coverage.info
