sudo: required
dist: precise
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq build-essential cmake curl lcov
  - gem install coveralls-lcov

before_script:
  - export CXX=$COMPILER
  - git submodule update --init
  - mkdir build
  - cd build
  - cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug ..

script:
  - cmake --build .
  - cmake --build . --target coveralls

after_success:
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info
  - lcov --list coverage.info
  - coveralls-lcov coverage.info

notifications:
  email: false
