#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# clone directory
clone_folder: c:\projects\gluino

#---------------------------------#
#       build configuration       #
#---------------------------------#

# scripts to run before build
before_build:
  # deleting Xamarin targets
  - del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"
  - cd c:\projects\gluino
  - mkdir build
  - cd build
  - cmake ..

build:
  project: c:\projects\gluino\build\gluino.sln

# scripts to run after build
after_build:
  - msbuild c:\projects\gluino\build\RUN_TESTS.vcxproj
